/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "FreeBSD asura.local 11.2-RELEASE-p4 amd64"
#define LGL_COMPILED "2018年 11月 4日 日曜日 03時44分26秒 JST"
#define LGL_RELEASED "Don Mai 22 22:08:00 CEST 2014"
#define LGL_VERSION "azf"
#define LGL_ID "92032848c138b2f33629ad24394d60a3787a1046"
