# ===================================================================
# ym-logic のための CMakeLists.txt
# ===================================================================


# ===================================================================
# パッケージの検査
# ===================================================================


# ===================================================================
# インクルードパスの設定
# ===================================================================

include_directories (
  private_include
  )


# ===================================================================
# サブディレクトリの設定
# ===================================================================

add_subdirectory(expr)
add_subdirectory(tvfunc)
add_subdirectory(npn)
add_subdirectory(tt)
add_subdirectory(bc)
add_subdirectory(sop)
add_subdirectory(factor)
add_subdirectory(rc)
add_subdirectory(dd)
add_subdirectory(djdec)
add_subdirectory(gtest)


# ===================================================================
#  ソースファイルの設定
# ===================================================================

set (ym_logic_SOURCES
  ${expr_SOURCES}
  ${tvfunc_SOURCES}
  ${npn_SOURCES}
  ${tt_SOURCES}
  ${bc_SOURCES}
  ${sop_SOURCES}
  ${factor_SOURCES}
  ${rectcover_SOURCES}
  ${dd_SOURCES}
  ${djdec_SOURCES}
  ${djdec_tv_SOURCES}
  )


# ===================================================================
#  ターゲットの設定
# ===================================================================

ym_add_object_library ( ym_logic
  ${ym_logic_SOURCES}
  )


# ===================================================================
#  インストールターゲットの設定
# ===================================================================
