# ===================================================================
# CMAKE のおまじない
# ===================================================================


# ===================================================================
# プロジェクト名，バージョンの設定
# ===================================================================


# ===================================================================
# オプション
# ===================================================================


# ===================================================================
# パッケージの検査
# ===================================================================


# ===================================================================
# ヘッダファイルの生成
# ===================================================================


# ===================================================================
# インクルードパスの設定
# ===================================================================
include_directories(
  )


# ===================================================================
#  マクロの定義
# ===================================================================


# ===================================================================
# サブディレクトリの設定
# ===================================================================

add_subdirectory ( gtest )


# ===================================================================
#  ソースの設定
# ===================================================================

set ( common_SOURCES
  ${CMAKE_CURRENT_SOURCE_DIR}/BitVector_constructor.cc
  ${CMAKE_CURRENT_SOURCE_DIR}/BitVector_misc.cc
  ${CMAKE_CURRENT_SOURCE_DIR}/BitVector_op1.cc
  ${CMAKE_CURRENT_SOURCE_DIR}/BitVector_op2.cc
  ${CMAKE_CURRENT_SOURCE_DIR}/VlMgr.cc
  ${CMAKE_CURRENT_SOURCE_DIR}/VlUdpVal.cc
  ${CMAKE_CURRENT_SOURCE_DIR}/VlValue.cc
  ${CMAKE_CURRENT_SOURCE_DIR}/VlValueRep.cc
  PARENT_SCOPE
  )


# ===================================================================
#  ターゲットの設定
# ===================================================================
