
# ===================================================================
# インクルードパスの設定
# ===================================================================
include_directories (
  )


# ===================================================================
# サブディレクトリの設定
# ===================================================================

add_subdirectory( gtest )


# ===================================================================
#  ソースファイルの設定
# ===================================================================

set ( fraig_SOURCES
  ${CMAKE_CURRENT_SOURCE_DIR}/FraigMgr.cc
  ${CMAKE_CURRENT_SOURCE_DIR}/FraigMgrImpl.cc
  ${CMAKE_CURRENT_SOURCE_DIR}/FraigNode.cc
  ${CMAKE_CURRENT_SOURCE_DIR}/FraigSat.cc
  )


# ===================================================================
# ターゲットの設定
# ===================================================================

ym_add_object_library( ym_fraig
  ${fraig_SOURCES}
  )