
# ===================================================================
# インクルードパスの設定
# ===================================================================


# ===================================================================
# サブディレクトリの設定
# ===================================================================


# ===================================================================
#  ソースファイルの設定
# ===================================================================


# ===================================================================
#  ターゲットの設定
# ===================================================================

add_executable( mincov
  mincov.cc
  $<TARGET_OBJECTS:ym_combopt_obj>
  $<TARGET_OBJECTS:ym_misc_obj>
  )

target_link_libraries ( mincov
  ${YM_LIB_DEPENDS}
  )

add_executable( mincov_d
  mincov.cc
  $<TARGET_OBJECTS:ym_combopt_obj_d>
  $<TARGET_OBJECTS:ym_misc_obj_d>
  )

target_compile_options ( mincov_d
  PRIVATE "-g"
  )

target_link_libraries ( mincov_d
  ${YM_LIB_DEPENDS}
  )
