# ===================================================================
# パッケージの検査
# ===================================================================


# ===================================================================
# インクルードパスの設定
# ===================================================================
include_directories(
  ${CMAKE_CURRENT_SOURCE_DIR}/private_include
  )


# ===================================================================
# サブディレクトリの設定
# ===================================================================

add_subdirectory( cgmgr )
add_subdirectory( ci )
add_subdirectory( clib )
add_subdirectory( dotlib )
add_subdirectory( mislib )


# ===================================================================
#  ソースファイルの設定
# ===================================================================

set (clib_SOURCES
  ${cgmgr_SOURCES}
  ${ci_SOURCES}
  ${clib_SOURCES}
  ${mislib_SOURCES}
  ${dotlib_SOURCES}
  )

# ===================================================================
#  ターゲットの設定
# ===================================================================

ym_add_object_library ( ym_clib
  ${clib_SOURCES}
  )


# ===================================================================
#  インストールターゲットの設定
# ===================================================================
