
# ===================================================================
# インクルードパスの設定
# ===================================================================

include_directories (
  private_include
  )


# ===================================================================
# サブディレクトリの設定
# ===================================================================

add_subdirectory( aig )
#add_subdirectory( blif )
add_subdirectory( io )
add_subdirectory( rwt )


# ===================================================================
#  ソースファイルの設定
# ===================================================================

set ( ym_aig_SOURCES
  ${aig_SOURCES}
  #${blif_SOURCES}
  ${io_SOURCES}
  ${rwt_SOURCES}
  )


# ===================================================================
# ターゲットの設定
# ===================================================================

ym_add_object_library ( ym_aig
  ${ym_aig_SOURCES}
  )


# ===================================================================
#  テストの設定
# ===================================================================


# ===================================================================
#  インストールターゲットの設定
# ===================================================================
