
# ===================================================================
# インクルードパスの設定
# ===================================================================


# ===================================================================
#  マクロの定義
# ===================================================================


# ===================================================================
# サブディレクトリの設定
# ===================================================================


# ===================================================================
#  npn_gen
# ===================================================================

set ( npn_gen_SOURCES
  npn_gen.cc
  )

add_executable ( npn_gen
  ${npn_gen_SOURCES}
  $<TARGET_OBJECTS:ym_logic_obj>
  $<TARGET_OBJECTS:ym_misc_obj>
  )

target_link_libraries ( npn_gen
  ${YM_LIB_DEPENDS}
  )


# ===================================================================
#  npn_gen_d
# ===================================================================

add_executable ( npn_gen_d
  ${npn_gen_SOURCES}
  $<TARGET_OBJECTS:ym_logic_obj_d>
  $<TARGET_OBJECTS:ym_misc_obj_d>
  )

target_compile_options ( npn_gen_d
  PRIVATE "-g"
  )

target_link_libraries ( npn_gen_d
  ${YM_LIB_DEPENDS}
  )
